site_name: Connect Guide
theme: 
  name: material
  palette:
    scheme: slate
    primary: cyan

site_author: Conch
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - def_list
  - attr_list
  - md_in_html

# nav:
#   - index.md
#   - getting-started.md